pub const SYS_EXIT: u64 = 93;
pub const SYS_LOAD_TRANSACTION: u64 = 2051;
pub const SYS_LOAD_SCRIPT: u64 = 2052;
pub const SYS_LOAD_TX_HASH: u64 = 2061;
pub const SYS_LOAD_SCRIPT_HASH: u64 = 2062;
pub const SYS_LOAD_CELL: u64 = 2071;
pub const SYS_LOAD_HEADER: u64 = 2072;
pub const SYS_LOAD_INPUT: u64 = 2073;
pub const SYS_LOAD_WITNESS: u64 = 2074;
pub const SYS_LOAD_CELL_BY_FIELD: u64 = 2081;
pub const SYS_LOAD_HEADER_BY_FIELD: u64 = 2082;
pub const SYS_LOAD_INPUT_BY_FIELD: u64 = 2083;
pub const SYS_LOAD_CELL_DATA_AS_CODE: u64 = 2091;
pub const SYS_LOAD_CELL_DATA: u64 = 2092;
pub const SYS_DEBUG: u64 = 2177;

pub const CKB_SUCCESS: u64 = 0;
pub const CKB_INDEX_OUT_OF_BOUND: u64 = 1;
pub const CKB_ITEM_MISSING: u64 = 2;
pub const CKB_LENGTH_NOT_ENOUGH: u64 = 3;

// pub const CKB_SOURCE_INPUT 1
// pub const CKB_SOURCE_OUTPUT 2
// pub const CKB_SOURCE_CELL_DEP 3
// pub const CKB_SOURCE_HEADER_DEP 4
// pub const CKB_SOURCE_GROUP_INPUT 0x0100000000000001
// pub const CKB_SOURCE_GROUP_OUTPUT 0x0100000000000002
//
// pub const CKB_CELL_FIELD_CAPACITY 0
// pub const CKB_CELL_FIELD_DATA_HASH 1
// pub const CKB_CELL_FIELD_LOCK 2
// pub const CKB_CELL_FIELD_LOCK_HASH 3
// pub const CKB_CELL_FIELD_TYPE 4
// pub const CKB_CELL_FIELD_TYPE_HASH 5
// pub const CKB_CELL_FIELD_OCCUPIED_CAPACITY 6
//
// pub const CKB_HEADER_FIELD_EPOCH_NUMBER 0
// pub const CKB_HEADER_FIELD_EPOCH_START_BLOCK_NUMBER 1
// pub const CKB_HEADER_FIELD_EPOCH_LENGTH 2
//
// pub const CKB_INPUT_FIELD_OUT_POINT 0
// pub const CKB_INPUT_FIELD_SINCE 1
